name = "Innerrealm SW"
author = "veselle"
version = "666.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "297225d5ac3cf9cb8bafa3ee3db0ddfabdaa067a14d3b449baffc21d8359ae94"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
