name = "Innerrealm SW"
author = "veselle"
version = "666.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d5b0c1565f55f0306e86a0b5b2849e1cccccb237ea4d75f57022cb22751e6ba"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
